### ISSUE TITLE
RtmpOnlyAudio seems to work with video also

### ISSUE THREAD

**Issue by kanoe92** [pedroSG94/rtmp-rtsp-stream-client-java#1023]
Hello, firstly thanks for your great library. I've got a question according to RtmpOnlyAudio. I'm using this to stream only audio inside app, but it seems to work with video also. It is returning 640x480 video size. Shouldn't it be video 0 size? 

`rtmpOnlyAudio.sentVideoFrames` is returning always 0, but video size is listed. Am I missing something? Is there some property to completly disable video?

![image](https://user-images.githubusercontent.com/11346730/147555958-2c3e423b-dae7-4ccf-bfc2-87179081314d.png)

**Comment by pedroSG94** [comment]
This error was solved in 2.1.5 library version. Please update it.

**Comment by MasTeh** [comment]
I have this problem too. On a xiaomi phone only. Everything works fine on other phone models. Version 2.1.5 
The video is not being sent. Only sound is sent. Please help )

**Comment by MasTeh** [comment]
> This error was solved in 2.1.5 library version. Please update it.

I have last version but this problem is still present on xiaomi phones. MIUI > 12
