### ISSUE TITLE
RTSP with UDP not work

### ISSUE THREAD

**Issue by Loren1994** [pedroSG94/rtmp-rtsp-stream-client-java#261]
Hi Pedro,
   My RTSP server (EasyDarWin) get little data (100+B per second) when I use UDP to push rtsp stream. TCP is normal.

**Comment by pedroSG94** [comment]
Fixed. I forgot add port to UDP packets: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/23f6dee2e1a7cffcf0bb1207626d8a44fda06641

**Comment by Loren1994** [comment]
ok. thank you .

**Comment by madmate** [comment]
Still not working for me :( with tcp everything works fine

My node-rtsp-rtmp-server receives data, multiple mb when the screen is changing, but the videostream in vlc stays black
