### ISSUE TITLE
java.lang.IllegalStateException: CameraDevice was already closed 

### ISSUE THREAD

**Issue by anarion-Vika** [pedroSG94/rtmp-rtsp-stream-client-java#528]
Hi! I have a crash while multiple presses at one moment switching the camera. It happened after the last update library to 1.7.8 version.

My logs:
2020-04-01 17:06:22.715 30768-30768/com.mylistory.android.dev E/libc: Access denied finding property "persist.vendor.camera.privapp.list"
2020-04-01 17:06:22.721 30768-31617/com.mylistory.android.dev E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2020-04-01 17:06:22.722 30768-31617/com.mylistory.android.dev E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2020-04-01 17:06:22.730 30768-30768/com.mylistory.android.dev E/Camera2ApiManager: Error
    java.lang.IllegalStateException: CameraDevice was already closed
        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2445)
        at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:1046)
        at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:1102)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:298)
        at com.pedro.encoder.input.video.Camera2ApiManager.disableLantern(Camera2ApiManager.java:295)
        at com.pedro.rtplibrary.base.Camera2Base.disableLantern(Camera2Base.java:147)
        at com.mylistory.stream.ui.tx.TxStreamFragment.switchCamera(TxStreamFragment.kt:179)
        at com.mylistory.stream.ui.tx.TxStreamFragment.access$switchCamera(TxStreamFragment.kt:52)
        at com.mylistory.stream.ui.tx.TxStreamFragment$onActivityCreated$1$1.onClick(TxStreamFragment.kt:102)
        at android.view.View.performClick(View.java:6612)
        at android.view.View.performClickInternal(View.java:6581)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25904)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:280)
        at android.app.ActivityThread.main(ActivityThread.java:6706)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

-------------------------------------------------------------------------------------------------
`override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)
        askPermission(Manifest.permission.CAMERA, Manifest.permission.RECORD_AUDIO) {
            rtmpCamera = RtmpCamera2(surfaceView, this)
                        rtmpCamera?.prepareVideo(PREFERED_WIDTH, PREFERED_HEIGHT, PREFERED_FPS,
                    AdapterBitrateParser.maxVideoBitrate, false, 90)
            surfaceView.holder.addCallback(this)
            switch_camera.setOnClickListener {
            try {
                rtmpCamera?.switchCamera()
                switchCamera() //(TxStreamFragment.kt:102)
            }catch (e: CameraAccessException) {
                e.printStackTrace()
            }
            catch (e:NullPointerException){
                e.printStackTrace()
            }
            catch (e: FileNotFoundException){
                e.printStackTrace()
            }
            }
            flash_camera.setOnClickListener { flash() }
        }.onDeclined {}
     }

private fun switchCamera() {
        try {
            flash_camera.setImageResource(R.drawable.stream_ic_flash_off)
            rtmpCamera?.disableLantern() // (TxStreamFragment.kt:179)
        } catch (e: CameraAccessException) {
            e.printStackTrace()
        }
        catch (e:NullPointerException){
            e.printStackTrace()
        }
        catch (e: FileNotFoundException){
            e.printStackTrace()
        }
    }`
------------------------------------------------------------------------------------
also if delete try-catch, there is the crash with the same code:
2020-04-01 17:06:23.569 30768-30768/com.mylistory.android.dev E/libc: Access denied finding property "persist.vendor.camera.privapp.list"
2020-04-01 17:06:23.575 30768-31617/com.mylistory.android.dev E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2020-04-01 17:06:23.816 30768-31617/com.mylistory.android.dev E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2020-04-01 17:06:23.818 30768-31701/com.mylistory.android.dev E/Camera2ApiManager: Error
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest$Builder android.hardware.camera2.CameraDevice.createCaptureRequest(int)' on a null object reference
        at com.pedro.encoder.input.video.Camera2ApiManager.drawSurface(Camera2ApiManager.java:159)
        at com.pedro.encoder.input.video.Camera2ApiManager.access$100(Camera2ApiManager.java:49)
        at com.pedro.encoder.input.video.Camera2ApiManager$1.onConfigured(Camera2ApiManager.java:122)

**Comment by Geremp** [comment]
I think you try to switch the camera but rtmpCamera object is not create yet.

This happen to me when i try to startpreview and just after switch camera :

`rtmpCamera2.startPreview(CameraHelper.Facing.BACK,i1,i2,orientation);
 changeCameraButton.performClick();`

The solution i found, is to wait before switch camera : 
`rtmpCamera2.startPreview(CameraHelper.Facing.BACK,i1,i2,orientation);
new Handler().postDelayed(new Runnable() {
        @Override
        public void run() {
          changeCameraButton.performClick();
        }
      }, 500);`

**Comment by pedroSG94** [comment]
This seems a bug
Are you using SurfaceView or OpenGlView?

**Comment by anarion-Vika** [comment]
> This seems a bug
> Are you using SurfaceView or OpenGlView?

com.pedro.rtplibrary.view.OpenGlView

**Comment by pedroSG94** [comment]
This should work now. The problem was with disableLantern. Try with version 1.7.9.

**Comment by anarion-Vika** [comment]
> This should work now. The problem was with disableLantern. Try with version 1.7.9.

Yes, this helped for the simple switch, but the first case of crash not resolved(the crash when multiple presses at one moment button for switching the camera. )

**Comment by anarion-Vika** [comment]
> I think you try to switch the camera but rtmpCamera object is not created yet.
> 
> This happen to me when i try to startpreview and just after switch camera :
> 
> `rtmpCamera2.startPreview(CameraHelper.Facing.BACK,i1,i2,orientation); changeCameraButton.performClick();`
> 
> The solution i found, is to wait before switch camera :
> `rtmpCamera2.startPreview(CameraHelper.Facing.BACK,i1,i2,orientation); new Handler().postDelayed(new Runnable() { @Override public void run() { changeCameraButton.performClick(); } }, 500);`

I try to add handler:
new function with handler:
------------------------------------
switch_camera.setOnClickListener {
                Handler().postDelayed({
                    rtmpCamera?.switchCamera()
                    switchCamera()
                }, 500)}
----
 private fun switchCamera() {
        Handler().postDelayed({
            flash_camera.setImageResource(R.drawable.stream_ic_flash_off)
            rtmpCamera?.disableLantern()
        }, 500)}
------------------------------------------
its not resolved problem with crash(
my new logs for this case : 

E/AndroidRuntime: FATAL EXCEPTION: Camera2ApiManager Id = 0
    Process: com.mylistory.android.dev, PID: 32337
    java.lang.IllegalStateException: CameraDevice was already closed
        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2445)
        at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(CameraDeviceImpl.java:653)
        at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:522)
        at com.pedro.encoder.input.video.Camera2ApiManager.startPreview(Camera2ApiManager.java:117)
        at com.pedro.encoder.input.video.Camera2ApiManager.onOpened(Camera2ApiManager.java:516)
        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:149)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:280)
        at android.os.HandlerThread.run(HandlerThread.java:65)
E/libc: Access denied finding property "persist.vendor.camera.privapp.list"
E/libc: Access denied finding property "vendor.camera.aux.packagelist"

**Comment by pedroSG94** [comment]
Try with this gradle (this is my last commit https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/d96b01fa3d913b504d4228edc44607bc4d4d2133):
```xml
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:d96b01fa3d'
```
I will do a release version if all is working fine

**Comment by anarion-Vika** [comment]
I tried it, but not work


E/AndroidRuntime: FATAL EXCEPTION: Camera2ApiManager Id = 1
    Process: com.mylistory.android.dev, PID: 16612
    java.lang.IllegalStateException: CameraDevice was already closed
        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2445)
        at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:1046)
        at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:1102)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:298)
        at com.pedro.encoder.input.video.Camera2ApiManager$1.onConfigured(Camera2ApiManager.java:124)
        at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0(CallbackProxies.java:53)
        at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:280)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by pedroSG94** [comment]
Try this:
```java
implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:047a0f5d8f'
```

**Comment by anarion-Vika** [comment]
Oh, it's much better! With this version I have the simple type of crash : 

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.hardware.camera2.CameraDevice.getId()' on a null object reference
        at com.pedro.encoder.input.video.Camera2ApiManager.switchCamera(Camera2ApiManager.java:400)
        at com.pedro.rtplibrary.base.Camera2Base.switchCamera(Camera2Base.java:691)
        at com.mylistory.stream.ui.tx.TxStreamFragment$onActivityCreated$1$1.onClick(TxStreamFragment.kt:106)

code TxStreamFragment.kt:106:
 switch_camera.setOnClickListener {
                rtmpCamera?.switchCamera()
                switchCamera()
            }

so I add the try-catch for this function. 
My result : 

 switch_camera.setOnClickListener {
            try {
                rtmpCamera?.switchCamera()
                switchCamera()
            }
            catch (e:NullPointerException){
                e.printStackTrace()
            }

It has resolved the last crash and good working now!
