### ISSUE TITLE
Audio video out of sync

### ISSUE THREAD

**Issue by ansariatif** [pedroSG94/rtmp-rtsp-stream-client-java#617]
Hi,
using library 1.8.3 . audio video out of sync

**Comment by pedroSG94** [comment]
Hello,
Can you give me more info to reproduce it?

Did you get this problem after few minutes or when you start stream? (specify me how many minutes)
Which mode are you using? (display, camera1, camera2, fromfile, etc)
Which view are you using? (SurfaceView, OpenGlView, background mode, etc)
Can you tell me device specifications? (API and model)
Can you tell me server and player used?

**Comment by ansariatif** [comment]
hi,
problem is continuing from start to end
using rtmpcamera1 
using surfaceview
test on android 7(Gionee) and android 10( samsung m30s) both have same problem.
testing on  NGINX And Adobe media server boths server has same problem.

i tested your sample code too. same problem in default rtmp and custom rtmp. but working fine in rtmpcamera2 in textureview  surfacemodeview but in android 7 it crash when stopstream.

working file with rtmpcamera1 with openglview in both device. .

and also need disable autofocus . is your libarary 1.8.3 has this feature.

**Comment by pedroSG94** [comment]
This seems that buffer to buffer encoding produce out of sync but surface to buffer work fine. I will check it.
Test with OpenGl example (this is using camera1).
Also, share me crash when you press stopstream to fix it.
About autofocus you need modify library for it because I always enable it. You can delete it here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera1ApiManager.java#L148

**Comment by pedroSG94** [comment]
Out of sync should be solved in 1.8.4:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/e7d26a123f3a7c1d3e654ce77fdb582cbcb31e14
Share me crash with camera2 in textureview/surfaceview and I can fix it.

**Comment by ansariatif** [comment]
2020-07-08 12:22:38.365 13894-14920/com.pedro.rtpstreamer E/AndroidRuntime: FATAL EXCEPTION: LegacyCameraCallback
    Process: com.pedro.rtpstreamer, PID: 13894
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest android.hardware.camera2.impl.CameraDeviceImpl$CaptureCallbackHolder.getRequest(int)' on a null object reference
        at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(CameraDeviceImpl.java:1758)
        at android.hardware.camera2.legacy.CameraDeviceUserShim$CameraCallbackThread$CallbackHandler.handleMessage(CameraDeviceUserShim.java:316)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ansariatif** [comment]
Crash in android 7 when stop stream. can you implement autofocus on off in feature because i am not using source code. i implement your library

**Comment by pedroSG94** [comment]
I can't see Camera2ApiManager line in that crash. Try share me a logcat with crash line in the class.
About autofocus, that is a good feature, I will try add this in the next release.

**Comment by ansariatif** [comment]
hi 
that is log cat error log when app crash.
thanks for new release now audio video  sync in 1.8.4.
whaiting for your new release with autofocus enable disbale feature.

**Comment by hjywyj** [comment]
May I ask if this problem has been resolved

**Comment by pedroSG94** [comment]
Hello,

This should be solved

**Comment by hjywyj** [comment]
> Hello,
> 
> This should be solved

But I still received this error message. My environment is Android7.0, RK3288 device.
When I create a RtmpCamera2, then startStream->stopStream.    it's work
Then I create a new RtmpCamera2, then startStream,throw this exception.

implementation 'com.github.pedroSG94.RootEncoder:library:2.4.4'

**Comment by hjywyj** [comment]
The RK3288 device of Android 7.0 is an external USB camera and has many strange problems.
When stopStream is called, the camera is also called close.
When calling startStream again, there is a probability that
`android.hardware.camera2.CameraAccessException: CAMERA_IN_USE (4): connectHelper:881: Higher-priority client using camera, ID "1" currently unavailable`
or
` android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): Camera service is currently unavailable
                                                                                                    	at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:257)
                                                                                                    	at com.pedro.encoder.input.video.Camera2ApiManager.openCameraId(Camera2ApiManager.java:822)
                                                                                                    	at com.pedro.encoder.input.video.Camera2ApiManager.openLastCamera(Camera2ApiManager.java:321)
                                                                                                    	at com.pedro.library.base.Camera2Base.startEncoders(Camera2Base.java:632)
                                                                                                    	at com.pedro.library.base.Camera2Base.startStream(Camera2Base.java:617)`

**Comment by hjywyj** [comment]
I'm going to use UVCCamera. After all, it doesn't have the weird problems above.
But I don’t know how stable it is on low-end devices. This requires a lot of testing.
Thanks!!!

**Comment by pedroSG94** [comment]
> > Hello,
> > This should be solved
> 
> But I still received this error message. My environment is Android7.0, RK3288 device. When I create a RtmpCamera2, then startStream->stopStream. it's work Then I create a new RtmpCamera2, then startStream,throw this exception.
> 
> implementation 'com.github.pedroSG94.RootEncoder:library:2.4.4'

Do you mean camera2 crash? I was talking about audio/video out of sync.

> android.hardware.camera2.CameraAccessException: CAMERA_IN_USE (4)

As you shared, the problem is that you have the previous camera without release.

According with your post the problem seems that you need release properly the camera before you create a new instance of RtmpCamera2. You need stop stream, record and preview before create a new RtmpCamera2 and use it. If possible you should avoid create a second instance of RtmpCamera2 and always use the same.
It is because Android only allow one instance of the camera at same time.

**Comment by hjywyj** [comment]
> > > Hello,
> > > This should be solved
> > 
> > 
> > But I still received this error message. My environment is Android7.0, RK3288 device. When I create a RtmpCamera2, then startStream->stopStream. it's work Then I create a new RtmpCamera2, then startStream,throw this exception.
> > implementation 'com.github.pedroSG94.RootEncoder:library:2.4.4'
> 
> Do you mean camera2 crash? I was talking about audio/video out of sync.
> 
> > android.hardware.camera2.CameraAccessException: CAMERA_IN_USE (4)
> 
> As you shared, the problem is that you have the previous camera without release.
> 
> According with your post the problem seems that you need release properly the camera before you create a new instance of RtmpCamera2. You need stop stream, record and preview before create a new RtmpCamera2 and use it. If possible you should avoid create a second instance of RtmpCamera2 and always use the same. It is because Android only allow one instance of the camera at same time.

Yes,I have stopped stream, record and preview,then I create instance throw Exception.
Android only allow one instance of the camera at same time? but camera2 allow two cameras to be opened simultaneously.
I am using an RK3288 device and have 2 external USB cameras. Using RtmpCamera2, I have been able to upload 2 video streams simultaneously. The error mentioned above was caused by frequent switching. Thanks!

**Comment by pedroSG94** [comment]
Yes, Android only allow one instance of the same camera at same time (open front and back camera is possible) but depend of the device open 2 different cameras at same time (front and back cameras) is not allowed. Open 2 times the front camera is not allowed.
Your case is a bit special because you are using external cameras so maybe we have an exception here.

If you use 2 cameras but only one preview you can switch without create a new RtmpCamera2 class using this methods:
```kotlin
rtmpCamera2.switchCamera()
rtmpCamera2.switchCamera(id: String)
```
The first one allow you switch using back and front default cameras of a normal phone and the second one allow you switch to a camera using the id of the camera
