### ISSUE TITLE
crash on stop service

### ISSUE THREAD

**Issue by assaadroid** [pedroSG94/rtmp-rtsp-stream-client-java#710]
I get this error when pressing on stop stream button, DisplayActivity
java.lang.IndexOutOfBoundsException: off=4, len=-3 out of bounds (size=5127)
        at java.nio.Buffer.checkBounds(Buffer.java:587)
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:285)
        at com.pedro.encoder.BaseEncoder.processInput(BaseEncoder.java:136)
        at com.pedro.encoder.BaseEncoder.inputAvailable(BaseEncoder.java:177)
        at com.pedro.encoder.BaseEncoder$2.onInputBufferAvailable(BaseEncoder.java:201)
        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1688)
        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1646)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by pedroSG94** [comment]
Are you using last commit?
This should be solved here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/b60bc6dc3cc5ca07707caa372dc8cbae74c8fb00

**Comment by assaadroid** [comment]
yes I am using gradle with version 1.9.4, I changed it to 938bcb1f90 and it seems to work perfectly,
 Btw I have set the time of animation in notification_anim to 66 bcz 500 is causing delay on server, is it possible to find another solution in the future (finding a way to render screen all the time so as to send video packets even when no screen change), Great job the project is wonderful. I will close this issue. 10x u.

**Comment by pedroSG94** [comment]
This could help you to render in display mode but It was not working well in all cases:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/view/GlInterface.java#L129
Try that and let me know if it works for you.

**Comment by MohammadRezaei92** [comment]
I have this error too:

```
Fatal Exception: java.lang.IndexOutOfBoundsException
off=0, len=-3 out of bounds (size=3584)
java.nio.Buffer.checkBounds (Buffer.java:587)
java.nio.DirectByteBuffer.put (DirectByteBuffer.java:285)
com.pedro.encoder.BaseEncoder.processInput (BaseEncoder.java:136)
com.pedro.encoder.BaseEncoder.inputAvailable (BaseEncoder.java:177)
com.pedro.encoder.BaseEncoder$2.onInputBufferAvailable (BaseEncoder.java:201)
```

**Comment by pedroSG94** [comment]
> I have this error too:
> 
> ```
> Fatal Exception: java.lang.IndexOutOfBoundsException
> off=0, len=-3 out of bounds (size=3584)
> java.nio.Buffer.checkBounds (Buffer.java:587)
> java.nio.DirectByteBuffer.put (DirectByteBuffer.java:285)
> com.pedro.encoder.BaseEncoder.processInput (BaseEncoder.java:136)
> com.pedro.encoder.BaseEncoder.inputAvailable (BaseEncoder.java:177)
> com.pedro.encoder.BaseEncoder$2.onInputBufferAvailable (BaseEncoder.java:201)
> ```

Are you using version 1.9.5?

**Comment by MohammadRezaei92** [comment]
> > I have this error too:
> > ```
> > Fatal Exception: java.lang.IndexOutOfBoundsException
> > off=0, len=-3 out of bounds (size=3584)
> > java.nio.Buffer.checkBounds (Buffer.java:587)
> > java.nio.DirectByteBuffer.put (DirectByteBuffer.java:285)
> > com.pedro.encoder.BaseEncoder.processInput (BaseEncoder.java:136)
> > com.pedro.encoder.BaseEncoder.inputAvailable (BaseEncoder.java:177)
> > com.pedro.encoder.BaseEncoder$2.onInputBufferAvailable (BaseEncoder.java:201)
> > ```
> 
> Are you using version 1.9.5?



> > I have this error too:
> > ```
> > Fatal Exception: java.lang.IndexOutOfBoundsException
> > off=0, len=-3 out of bounds (size=3584)
> > java.nio.Buffer.checkBounds (Buffer.java:587)
> > java.nio.DirectByteBuffer.put (DirectByteBuffer.java:285)
> > com.pedro.encoder.BaseEncoder.processInput (BaseEncoder.java:136)
> > com.pedro.encoder.BaseEncoder.inputAvailable (BaseEncoder.java:177)
> > com.pedro.encoder.BaseEncoder$2.onInputBufferAvailable (BaseEncoder.java:201)
> > ```
> 
> Are you using version 1.9.5?

I'm using:
`implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:f2b54cfd45'`

**Comment by pedroSG94** [comment]
Can you reproduce the problem with app example?
Device model and API?
Can you tell me mode used? If you are using display mode, which audio are you using (microphone or internal)?
Also share me audio configuration to try reproduce the problem.

**Comment by MohammadRezaei92** [comment]
I had this issue in various device
![image](https://user-images.githubusercontent.com/14319444/99154762-7187ba80-26c7-11eb-98bc-be33112414b0.png)
- It happens on RtmpDisplay when stop called.
- I use the microphone mode

**Comment by pedroSG94** [comment]
This should be fixed now:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/dd3b349c8dcda7998e40bcec55cc37180488cd1a
Try with this gradle:
```gradle
	        implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:dd3b349c8d'
```

**Comment by MohammadRezaei92** [comment]
> This should be fixed now:
> [dd3b349](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/dd3b349c8dcda7998e40bcec55cc37180488cd1a)
> Try with this gradle:
> 
> ```groovy-gradle
> 	        implementation 'com.github.pedroSG94:rtmp-rtsp-stream-client-java:dd3b349c8d'
> ```

This error still happen with this version
![image](https://user-images.githubusercontent.com/14319444/103155746-c2ef9300-47b7-11eb-9df6-c8fea6dcbcc5.png)

**Comment by pedroSG94** [comment]
Sorry for late response I was in holydays.

Try with last version. I did a fix for it:
```gradle
  implementation 'com.github.pedroSG94.rtmp-rtsp-stream-client-java:rtplibrary:1.9.6'

```
