### ISSUE TITLE
Rtsp-simple-server not working

### ISSUE THREAD

**Issue by t3therdev** [pedroSG94/rtmp-rtsp-stream-client-java#739]
Hi, we are trying to test the sample project with a very well known open source rtsp server/proxy. FFmpeg and other projects work fine. We cannot get rtsp push streaming from any of your samples to work.

You can find the project here, with precompiled binaries:
https://github.com/aler9/rtsp-simple-server

We are using rtsp and trying to simply push video to a server for testing, but we just get immediate retry errors. 

Please let us know if you can confirm if it works or not.

**Comment by pedroSG94** [comment]
I fixed it for RTSP/UDP:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/1199744d5218422ae6aba29ea3bfdb6a5351c28a
Open custom rtsp example, in menu select udp and try.
RTSP/TCP is not working for now, I'm looking the reason.

**Comment by StewardH** [comment]
Hi Pedro thanks for the quick reply to the issue above. I have tested the same server/RSTP-UDP streaming configuration and the problem is still there. I suspect that is because the changes you added in the 1199744 commit do not appear in the official maven repository that i am using (https://jitpack.io).  For example the createH264Body in Body.java (from maven) is still using RtpConstants.payloadType instead of the RtpConstants.payloadTypeVideo. If that is the case please update maven. Otherwise why would  the custom rtsp example not work on UDP?

**Comment by t3therdev** [comment]
Is it possible to also fix it for TCP streaming?

**Comment by StewardH** [comment]
I just tested the 1.9.7 release and I can confirm that the RTSP over TCP is fixed. Thank you.
However the UDP is not working yet.

**Comment by pedroSG94** [comment]
This is duplicated now. I will close this one and wait for your reply in the other issue.
