### ISSUE TITLE
wowza cloud

### ISSUE THREAD

**Issue by natxopedreira** [pedroSG94/rtmp-rtsp-stream-client-java#770]
Hello

Im trying your lib and im having problems trying to send a rtsp stream to wowza cloud using a trial demo account. I get audio but no image.... see some issues related that say its fixed but... maybe is broken again?

Gracias!!

**Comment by natxopedreira** [comment]
note that rtmp works, this only happens on rtsp

**Comment by pedroSG94** [comment]
Fixed: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/commit/7c838102729d66c32edbcbfe4330bb06219af779
Let me know if all is working for you. If not report me logcat connection.

**Comment by natxopedreira** [comment]
Thank you!!!!, sadly still not able to view, but have to say that i'm not sure is your fault or a wowza issue. Sadly i was not able to found another online service that supports rtsp to test

Video shows "static" on preview window but is not able to show on webplayer, and streams sometimes goes to paused.... extrange because in rtmp works without any issue

Logcat on error

`2021-02-05 00:55:21.184 32114-32114/com.pedro.rtpstreamer E/DisplayService: RTP Display service create
2021-02-05 00:55:21.194 32114-32114/com.pedro.rtpstreamer E/DisplayService: RTP Display service started
2021-02-05 00:55:21.332 32114-25261/com.pedro.rtpstreamer E/C2AllocatorIon: >>>SEC mapUsage Mapper1 2000000
2021-02-05 00:55:21.332 32114-25261/com.pedro.rtpstreamer E/C2AllocatorIon: >>>SEC C2AllocatorIon::mapUsage ion_is_legacy++++++++
2021-02-05 00:55:21.332 32114-25261/com.pedro.rtpstreamer E/C2AllocatorIon: >>>SEC mapUsage	0, 2000000
2021-02-05 00:55:22.897 32114-25270/com.pedro.rtpstreamer E/DisplayService: RTP service destroy
`

in verbose
`2021-02-05 00:56:07.985 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 315
2021-02-05 00:56:08.032 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Video, size: 248
2021-02-05 00:56:08.032 32114-25276/com.pedro.rtpstreamer I/BaseSenderReport: wrote report: Audio, packets: 258, octet: 108398
2021-02-05 00:56:08.064 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 271
2021-02-05 00:56:08.064 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 260
2021-02-05 00:56:08.065 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 298
2021-02-05 00:56:08.144 32114-25261/com.pedro.rtpstreamer D/BufferPoolAccessor: bufferpool2 0x78d3c96e20 : 5(25600 size) total buffers - 3(15360 size) used buffers - 1198/1203 (recycle/alloc) - 5/2331 (fetch/transfer)
2021-02-05 00:56:08.145 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 261
2021-02-05 00:56:08.146 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 258
2021-02-05 00:56:08.225 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 265
2021-02-05 00:56:08.225 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 281
2021-02-05 00:56:08.226 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 265
2021-02-05 00:56:08.305 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 275
2021-02-05 00:56:08.306 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 296
2021-02-05 00:56:08.385 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 282
2021-02-05 00:56:08.385 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 266
2021-02-05 00:56:08.386 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 285
2021-02-05 00:56:08.466 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 264
2021-02-05 00:56:08.467 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Audio, size: 265
2021-02-05 00:56:08.542 32114-25276/com.pedro.rtpstreamer I/BaseRtpSocket: wrote packet: Video, size: 248`

**Comment by pedroSG94** [comment]
Can you try with default example to discard rtsp module problems?
I think that your problem is related with display mode but it is weird that rtmp is working

**Comment by natxopedreira** [comment]
Sorry i did not mentioned but im testing with your sample app to discard code problem in my side.

Yep rtmp works ok

**Comment by pedroSG94** [comment]
I mean using Default RTSP or OpenGL RTSP buttons instead of display rtmp or rtsp

**Comment by natxopedreira** [comment]
yep sorry, i tried that, default RTPS and also custom to play with setings to see if found something but same behaviour all the time.

Video Thumb shows a image but webplayer no, and also static panel goes sometimes to paused >>> loading >>> normal

screeshot
[https://ibb.co/NVXwwrV](https://ibb.co/NVXwwrV)

**Comment by pedroSG94** [comment]
I will check it.
Anyway if I open stream with vlc it is working for me.
You can use HLS url for it

**Comment by natxopedreira** [comment]
thank you!

**Comment by natxopedreira** [comment]
sorry, you also see the pause>>loading>>normal behaviour¿ or is just me

**Comment by pedroSG94** [comment]
Yes, I see that sometimes but I can still reproduce stream in VLC without problem

**Comment by natxopedreira** [comment]
ok!!!! yes i tested and able to see.... but stops :(... even on custom settings with low res and bitrate and im under a "conexion de fibra", rtmp works much better.

thank you for taking a look
